### ISSUE TITLE
Fedora Rawhide

### ISSUE THREAD

**Issue by Leleat** [Schneegans/gnome-shell-pod#8]
Hi,

wanted to ask if it's possible to provide something like this for Fedora Rawhide so that we could test extensions in an up-to-date GNOME Shell?

**Comment by Schneegans** [comment]
Hi there! Thanks for the suggestion! I experienced some issues with GNOME Shell in pre-release containers. However, I think it's a great idea to have a "rawhide" container next to the tagged versions. I could setup the GitHub actions in such a way that the container is rebuilt every now and then, maybe weekly.
